default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_manager_development

  username: postgres

  password: 1amr00t

  host: localhost

  port: 5432

  #schema_search_path: myapp,sharedapp,public

  #min_messages: notice

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  database: task_manager_production
  username: task_manager
  password: <%= ENV['TASK_MANAGER_DATABASE_PASSWORD'] %>
